### ISSUE TITLE
Feature Request: allow interval greater than 30 - up to 60

### ISSUE THREAD

**Issue by mars3142** [Fleximex/interval_time_picker#5]
I need a time picker, where I can pick only the hours, so an interval of 60 would be great. I know, I could use another UI widget for that, but we want to be consistent, that's why an interval of 60 is the best solution for use.

**Comment by Fleximex** [comment]
An interval of 60 has been added to version 1.1.0 (for Flutter 2.x.x) and 2.0.0 (for Flutter 3.1.0 and up)
